### ISSUE TITLE
一部PHPファイルについて

### ISSUE THREAD

**Issue by qeita** [tmtystm15/09_36_tomitayasutomo#1]
@tmtystm15  
  
課題提出お疲れ様でした。チューターのヤギです。  
取り急ぎ確認しまして、1点 registration.php のファイルのコードが表示されず、登録処理の確認ができない状況です。  
  
registration.php：  
[https://github.com/tmtystm15/09_36_tomitayasutomo/blob/master/registration.php](https://github.com/tmtystm15/09_36_tomitayasutomo/blob/master/registration.php)  
  
その他のphpファイル：  
[https://github.com/tmtystm15/09_36_tomitayasutomo/blob/master/login.php](https://github.com/tmtystm15/09_36_tomitayasutomo/blob/master/login.php)  
  
おそらくregistration.phpのみ実ファイルでない可能性(エイリアスをあげているとか)がありますので、一度ご確認いただければと思います。

**Comment by tmtystm15** [comment]
ヤギさん

お疲れ様です。DEV9期３６番富田です。
ご指摘ありがとうございます。
registration.phpがエイリアスでアップしてましたので、ファイルアップし直しました。
ご確認いただけますと幸いです。

宜しくお願い致します。

**Comment by qeita** [comment]
@tmtystm15  
  
ありがとうございます。  
遅くなってしまいすみません。  
更新されたregistration.phpで動作確認することができました。  
  
問題ないようなので、こちらのissueはクローズ致しますね
